export const SUBMIT_FORM_INITIATED = 'SUBMIT_FORM_INITIATED';
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR';
export const REVIEW_STEP = 'REVIEW_STEP';
export const EDIT_FORM = 'EDIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';